export default function Book() {
  return (
    <section>
      <div>
        <h2>A</h2>
      </div>
      <div>
        <h2>B</h2>
      </div>
      <div>
        <h2>C</h2>
      </div>
      <div>
        <h2>D</h2>
      </div>
      <div>
        <h2>E</h2>
      </div>
      <div>
        <h2>F</h2>
      </div>
      <div>
        <h2>G</h2>
      </div>
      <div>
        <h2>H</h2>
      </div>
      <div>
        <h2>I</h2>
      </div>
      <div>
        <h2>J</h2>
      </div>
      <div>
        <h2>K</h2>
      </div>
      <div>
        <h2>L</h2>
      </div>
      <div>
        <h2>M</h2>
      </div>
      <div>
        <h2>N</h2>
      </div>
      <div>
        <h2>O</h2>
      </div>
      <div>
        <h2>P</h2>
      </div>
      <div>
        <h2>Q</h2>
      </div>
      <div>
        <h2>R</h2>
      </div>
      <div>
        <h2>S</h2>
      </div>
      <div>
        <h2>T</h2>
      </div>
      <div>
        <h2>U</h2>
      </div>
      <div>
        <h2>V</h2>
      </div>
      <div>
        <h2>W</h2>
      </div>
      <div>
        <h2>X</h2>
      </div>
      <div>
        <h2>Y</h2>
      </div>
      <div>
        <h2>Z</h2>
      </div>
    </section>
  )
}